"""Fixture builders for the ``stig-runner`` plugin: a CKL checklist and a repository to probe.

Why the checklist is assembled by hand here rather than with ``xml.etree``
-------------------------------------------------------------------------
``ckl.py`` reads and writes CKL with ``xml.etree.ElementTree``. If this fixture used the same
library, the round-trip test would only prove ElementTree agrees with itself. So
:func:`build_ckl` emits the bytes with plain string formatting, copying the byte layout of a
real STIG Viewer 3.7.0 export: an XML declaration with double quotes, the
``<!--DISA STIG Viewer :: 3.7.0 -->`` comment, tab indentation, LF line endings, **no trailing
newline** after ``</CHECKLIST>``, empty elements in long form (``<HOST_NAME></HOST_NAME>``),
``&amp;``/``&lt;``/``&gt;`` for the three text-critical characters and ``&#xD;`` for a carriage
return inside element text. That last one is the trap the round trip has to survive: an XML
parser turns ``&#xD;`` into ``\r`` and a naive serialiser writes the raw byte back, silently
rewriting the file.

The rule content is real
------------------------
:data:`RULES` carries six rules copied verbatim from a checklist generated by STIG Viewer
3.7.0 for the Application Security and Development STIG V6R4 (``version 6``,
``Release: 4 Benchmark Date: 01 Oct 2025``), including their real ``Vuln_Num``, ``Rule_ID``,
``Rule_Ver``, CCI references and legacy ids. STIG content is a work of the US Government and
is not subject to copyright. The eight were chosen so the probe tests have something to find:
seven have entries in ``asd_probes.PROBES``, between them exercising all four probe kinds, and
one (APSC-DV-003236, the incident response plan) deliberately has none; APSC-DV-002490's check text contains ``<script>`` and ``<img …>``,
APSC-DV-002630's contains ``POA&Ms``, and APSC-DV-003236's fix text contains ``&#xD;`` - so
one fixture exercises each escaping rule above.

Note for anyone extending this: every one of the 286 rules in ASD V6R4 has
``Documentable`` = ``false``, so there is no "Documentable rule" to include.
"""
from __future__ import annotations

import io
import re
from pathlib import Path

#: Header comment of the reference export; ``ckl.py`` preserves whatever the input carried.
HEADER_COMMENT = "<!--DISA STIG Viewer :: 3.7.0 -->"

#: The twelve ``<ASSET>`` children, in the document order STIG Viewer writes them.
ASSET_FIELDS = ("ROLE", "ASSET_TYPE", "HOST_NAME", "HOST_IP", "HOST_MAC", "HOST_FQDN",
                "TARGET_COMMENT", "TECH_AREA", "TARGET_KEY", "WEB_OR_DATABASE", "WEB_DB_SITE",
                "WEB_DB_INSTANCE")

#: A blank asset block as STIG Viewer writes it for a new checklist.
DEFAULT_ASSET = {"ROLE": "None", "ASSET_TYPE": "Computing", "TARGET_KEY": "4093",
                 "WEB_OR_DATABASE": "false"}

#: ``<STIG_INFO>`` SI_DATA pairs, in order, from the reference export.
STIG_INFO = [
    ("version", "6"),
    ("classification", "UNCLASSIFIED"),
    ("customname", ""),
    ("stigid", "Application_Security_Development_STIG"),
    ("description", ""),
    ("releaseinfo", "Release: 4 Benchmark Date: 01 Oct 2025"),
    ("title", "Application Security and Development Security Technical Implementation Guide"),
    ("uuid", "8a2162f9-56dd-4978-8924-a5a6f633b6bb"),
    ("notice", "terms-of-use"),
    ("source", "Unknown"),
]

#: Eight real ASD V6R4 rules, each a list of ``(VULN_ATTRIBUTE, ATTRIBUTE_DATA)`` pairs in
#: document order. ``LEGACY_ID`` and ``CCI_REF`` repeat; every other attribute appears once.
RULES = [
    [
        ('Vuln_Num', 'V-222387'),
        ('Severity', 'medium'),
        ('Group_Title', 'SRG-APP-000001'),
        ('Rule_ID', 'SV-222387r960735_rule'),
        ('Rule_Ver', 'APSC-DV-000010'),
        ('Rule_Title', 'The application must provide a capability to limit the number of logon sessions per user.'),
        ('Vuln_Discuss', 'Application management includes the ability to control the number of users and user sessions that utilize an application. Limiting the number of allowed users and sessions per user is helpful in limiting risks related to DoS attacks.\n\nThis requirement may be met via the application or by utilizing information system session control provided by a web server or other underlying solution that provides specialized session management capabilities.\n\nIf it has been specified that this requirement will be handled by the application, the capability to limit the maximum number of concurrent single user sessions must be designed and built into the application.\n\nThis requirement addresses concurrent sessions for individual system accounts and does not address concurrent sessions by single users via multiple system accounts.\n\nThe maximum number of concurrent sessions should be defined based upon mission needs and the operational environment for each system.'),
        ('IA_Controls', ''),
        ('Check_Content', 'For production environments;  Review the system documentation, identify the number of application user logon sessions allowed per user, identify the methods utilized for user session management or have application administrator describe how the application implements user session management.\n\nUtilize the management interface that is used to set the user session values, or examine configuration files in order to review user session configuration settings.\n\nEnsure the number of sessions allowed per user is specified in accordance with the organizational requirements.\n\nFor development environments;  have the developer provide design documentation or demonstrate how the application is designed to limit the number of simultaneous user logon sessions.\n\nIf the application is not configured to limit the number of logon sessions per user as defined by the organization, this is a finding.'),
        ('Fix_Text', 'Design and configure the application to specify the number of logon sessions that are allowed per user.'),
        ('False_Positives', ''),
        ('False_Negatives', ''),
        ('Documentable', 'false'),
        ('Mitigations', ''),
        ('Potential_Impact', ''),
        ('Third_Party_Tools', ''),
        ('Mitigation_Control', ''),
        ('Responsibility', ''),
        ('Security_Override_Guidance', ''),
        ('Check_Content_Ref', 'M'),
        ('Weight', '10.0'),
        ('Class', 'Unclassified'),
        ('STIGRef', 'Application Security and Development Security Technical Implementation Guide :: Version 6, Release: 4 Benchmark Date: 01 Oct 2025'),
        ('STIG_UUID', '927354eb-3789-4a7d-957b-c1feb6d6b8c8'),
        ('LEGACY_ID', 'V-69239'),
        ('LEGACY_ID', 'SV-83861'),
        ('CCI_REF', 'CCI-000054'),
    ],
    [
        ('Vuln_Num', 'V-222396'),
        ('Severity', 'medium'),
        ('Group_Title', 'SRG-APP-000014'),
        ('Rule_ID', 'SV-222396r960759_rule'),
        ('Rule_Ver', 'APSC-DV-000160'),
        ('Rule_Title', 'The application must implement DoD-approved encryption to protect the confidentiality of remote access sessions.'),
        ('Vuln_Discuss', 'Without confidentiality protection mechanisms, unauthorized individuals may gain access to sensitive information via a remote access session.\n\nRemote access is access to DoD nonpublic information systems by an authorized user (or an information system) communicating through an external, non-organization-controlled network. Remote access methods include, for example, dial-up, broadband, and wireless.\n\nEncryption provides a means to secure the remote connection to prevent unauthorized access to the data traversing the remote access connection thereby providing a degree of confidentiality. The encryption strength of mechanism is selected based on the security categorization of the information.'),
        ('IA_Controls', ''),
        ('Check_Content', 'Review the application documentation and interview the system administrator.\n\nIdentify the application encryption capabilities and methods for implementing encryption protection.\n\nFor web based applications; open the web browser and access the website URL. Use the browser and determine if the session is protected via TLS. A secure connection is usually indicated in the upper left hand corner of the URL by a padlock icon. Click on the padlock icon and examine the connection information. Determine if TLS encryption is used to secure the session.\n\nFor non-web based applications, determine the TCP/IP port, protocol and method used for establishing client connections to the remote server. Review application configuration settings to ensure encryption is specified and  via TLS.\n\nIf the connection is not secured with TLS, this is a finding.'),
        ('Fix_Text', 'Design and configure applications to use TLS encryption to protect the confidentiality of remote access sessions.'),
        ('False_Positives', ''),
        ('False_Negatives', ''),
        ('Documentable', 'false'),
        ('Mitigations', ''),
        ('Potential_Impact', ''),
        ('Third_Party_Tools', ''),
        ('Mitigation_Control', ''),
        ('Responsibility', ''),
        ('Security_Override_Guidance', ''),
        ('Check_Content_Ref', 'M'),
        ('Weight', '10.0'),
        ('Class', 'Unclassified'),
        ('STIGRef', 'Application Security and Development Security Technical Implementation Guide :: Version 6, Release: 4 Benchmark Date: 01 Oct 2025'),
        ('STIG_UUID', '44f9b62d-b610-400a-88c8-38797311c782'),
        ('LEGACY_ID', 'SV-83879'),
        ('LEGACY_ID', 'V-69257'),
        ('CCI_REF', 'CCI-000068'),
    ],
    [
        ('Vuln_Num', 'V-222571'),
        ('Severity', 'medium'),
        ('Group_Title', 'SRG-APP-000514'),
        ('Rule_ID', 'SV-222571r1117181_rule'),
        ('Rule_Ver', 'APSC-DV-002030'),
        ('Rule_Title', 'The application must utilize FIPS-validated cryptographic modules when generating cryptographic hashes.'),
        ('Vuln_Discuss', 'Use of weak or untested encryption algorithms undermines the purposes of utilizing encryption to protect data. The application must implement cryptographic modules adhering to the higher standards approved by the federal government since this provides assurance they have been tested and validated.\n\nIf the application resides on a National Security System (NSS) it must not use a hashing algorithm weaker than SHA-384.'),
        ('IA_Controls', ''),
        ('Check_Content', 'Review the application components and the application requirements to determine if the application is capable of generating cryptographic hashes.\n\nReview the application documentation and interview the application developer or administrator to identify the cryptographic modules used by the application.\n\nIf hashing of application components has been identified in the application security plan as not being required and if a documented acceptance of risk is provided, this is not a finding.\n\nHave the application admin or the developer demonstrate how the application generates hashes and what hashing algorithms are used when generating a hash value.\n\nWhile SHA1 is currently FIPS-140-2 approved, due to known vulnerabilities with this algorithm, DoD PKI policy prohibits the use of SHA1 as of December 2016.  See DoD CIO Memo Subject: Revised Schedule to Update DoD Public Key Infrastructure Certificates to Secure Hash Algorithm-256. \n\nIf the application resides on a National Security System (NSS) and uses an algorithm weaker than SHA-384, this is a finding.\n\nIf FIPS-validated cryptographic modules are not used when generating hashes or if the application is configured to use the MD5 or SHA1 hashing algorithm, this is a finding.'),
        ('Fix_Text', 'Configure the application to use a FIPS-validated hashing algorithm when creating a cryptographic hash.'),
        ('False_Positives', ''),
        ('False_Negatives', ''),
        ('Documentable', 'false'),
        ('Mitigations', ''),
        ('Potential_Impact', ''),
        ('Third_Party_Tools', ''),
        ('Mitigation_Control', ''),
        ('Responsibility', ''),
        ('Security_Override_Guidance', ''),
        ('Check_Content_Ref', 'M'),
        ('Weight', '10.0'),
        ('Class', 'Unclassified'),
        ('STIGRef', 'Application Security and Development Security Technical Implementation Guide :: Version 6, Release: 4 Benchmark Date: 01 Oct 2025'),
        ('STIG_UUID', 'be43fae8-1fea-4c3a-9e60-e00b1985ec65'),
        ('LEGACY_ID', 'SV-84815'),
        ('LEGACY_ID', 'V-70193'),
        ('CCI_REF', 'CCI-002450'),
    ],
    [
        ('Vuln_Num', 'V-222602'),
        ('Severity', 'high'),
        ('Group_Title', 'SRG-APP-000251'),
        ('Rule_ID', 'SV-222602r961158_rule'),
        ('Rule_Ver', 'APSC-DV-002490'),
        ('Rule_Title', 'The application must protect from Cross-Site Scripting (XSS) vulnerabilities.'),
        ('Vuln_Discuss', 'XSS attacks are essentially code injection attacks against the various language interpreters contained within the browser. XSS can be executed via HTML, JavaScript, VBScript, ActiveX; essentially any scripting language a browser is capable of processing.\n\nXSS vulnerabilities are created when a website does not properly sanitize, escape, or encode user input. For example, "&lt;" is the HTML encoding for the "<" character. If the encoding is performed, the script code will not execute.\n\nThere are 3 parties involved in an XSS attack, the attacker, the trusted and vulnerable website, and the victim. An attacker will take advantage of a vulnerable website that does not properly validate user input by inserting malicious code into any data entry field.\n\nWhen the victim visits the trusted website and clicks on the malicious link left by the attacker, the attacker’s script is executed in the victims browser with the trust permissions assigned to the site.\n\nThere are several different types of XSS attack and the complete details regarding XSS cannot be described completely here.\n\nTo address the issue of XSS, web application developers must escape, encode or otherwise validate all user input that is processed and output by the web server. They should also use web templates or a web development framework that provides the capability to encode or otherwise validate user input.\n\nExamples of XSS vulnerabilities can be obtained from the Open Web Application Security Project (OWASP) website.\n  \nThe site is available by pointing your browser to https://www.owasp.org.'),
        ('IA_Controls', ''),
        ('Check_Content', 'Review the application documentation and the vulnerability assessment scan results from automated vulnerability assessment tools.\n\nVerify scan configuration settings include web-based applications settings which include XSS tests.\n\nReview scan results for XSS vulnerabilities.\n\nIf the scan results indicate aspects of the application are vulnerable to XSS, request subsequent scan data that shows the XSS vulnerabilities previously detected have been fixed.\n\nIf results that show compliance are not available, request proof of any steps that have been taken to mitigate the risk. This can include using network-based IPS to detect and prevent XSS attacks from occurring.\n\nIf scan results are not available, perform manual testing in various data entry fields to determine if XSS exist.\n\nNavigate through the web application as a regular user and identify any data entry fields where data can be input.\n\nInput the following strings:\n\n<script>alert(\'hello\')</script>\n<img src=x onerror="alert(document.cookie);"\n\nIf the script pop up box is displayed, or if scan reports show unremediated XSS results and no mitigating steps have been taken, this is a finding.'),
        ('Fix_Text', 'Verify user input is validated and encode or escape user input to prevent embedded script code from executing.\n\nDevelop your application using a web template system or a web application development framework that provides auto escaping features rather than building your own escape logic.'),
        ('False_Positives', ''),
        ('False_Negatives', ''),
        ('Documentable', 'false'),
        ('Mitigations', ''),
        ('Potential_Impact', ''),
        ('Third_Party_Tools', ''),
        ('Mitigation_Control', ''),
        ('Responsibility', ''),
        ('Security_Override_Guidance', ''),
        ('Check_Content_Ref', 'M'),
        ('Weight', '10.0'),
        ('Class', 'Unclassified'),
        ('STIGRef', 'Application Security and Development Security Technical Implementation Guide :: Version 6, Release: 4 Benchmark Date: 01 Oct 2025'),
        ('STIG_UUID', 'fe7973a8-1617-4ced-b4d0-02031f2805c1'),
        ('LEGACY_ID', 'SV-84879'),
        ('LEGACY_ID', 'V-70257'),
        ('CCI_REF', 'CCI-001310'),
    ],
    [
        ('Vuln_Num', 'V-222607'),
        ('Severity', 'high'),
        ('Group_Title', 'SRG-APP-000251'),
        ('Rule_ID', 'SV-222607r961158_rule'),
        ('Rule_Ver', 'APSC-DV-002540'),
        ('Rule_Title', 'The application must not be vulnerable to SQL Injection.'),
        ('Vuln_Discuss', 'SQL Injection is a code injection attack against database applications. Malicious SQL statements are inserted into an application data entry field where they are submitted to the database and executed. This is a direct result of not validating input that is used by the application to perform a command or execute an action.\n\nSuccessful attacks can read data, write data, execute administrative functions within the database, shutdown the DBMS, and in some cases execute OS commands.\n\nBest practices to reduce the potential for SQL Injection vulnerabilities include:\n\nNot using concatenation or replacement to build SQL queries.\n\nUsing prepared statements with parameterized queries that have been tested and validated not to be vulnerable to SQL Injection.\n\nUsing stored procedures that have been tested and validated not to be vulnerable to SQL Injection.\n\nEscaping all user supplied input.\n\nAdditional steps to prevent SQL Injection can be found at the OWASP website:\n\nhttps://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet'),
        ('IA_Controls', ''),
        ('Check_Content', 'Review the application documentation and interview the application administrator.\n\nRequest the latest vulnerability scan test results.\n\nVerify the scan configuration is configured to test for SQL injection flaws.\n\nReview the scan results to determine if any SQL injection flaws were detected during application testing.\n\nIf SQL injection flaws were discovered, request a subsequent scan that will show that the issues have been remediated.\n\nIf the scan results are not available, identify the database product in use and refer to the OWASP web application testing guide for detailed instructions on performing a manual SQL injection test. The instructions are located here and many tests are organized by database product:\n\nhttps://www.owasp.org/index.php/Testing_for_SQL_Injection_%28OTG-INPVAL-005%29\n\nIf the application is vulnerable to SQL injection attack, contains SQL injection flaws, or if scan results do not exist, this is a finding.'),
        ('Fix_Text', 'Modify the application and remove SQL injection vulnerabilities.'),
        ('False_Positives', ''),
        ('False_Negatives', ''),
        ('Documentable', 'false'),
        ('Mitigations', ''),
        ('Potential_Impact', ''),
        ('Third_Party_Tools', ''),
        ('Mitigation_Control', ''),
        ('Responsibility', ''),
        ('Security_Override_Guidance', ''),
        ('Check_Content_Ref', 'M'),
        ('Weight', '10.0'),
        ('Class', 'Unclassified'),
        ('STIGRef', 'Application Security and Development Security Technical Implementation Guide :: Version 6, Release: 4 Benchmark Date: 01 Oct 2025'),
        ('STIG_UUID', '0be00cd4-3232-459a-933c-c08dff0f8347'),
        ('LEGACY_ID', 'SV-84889'),
        ('LEGACY_ID', 'V-70267'),
        ('CCI_REF', 'CCI-001310'),
    ],
    [
        ('Vuln_Num', 'V-222614'),
        ('Severity', 'medium'),
        ('Group_Title', 'SRG-APP-000456'),
        ('Rule_ID', 'SV-222614r1117151_rule'),
        ('Rule_Ver', 'APSC-DV-002630'),
        ('Rule_Title', 'Security-relevant software updates and patches must be kept up to date.'),
        ('Vuln_Discuss', 'Security flaws with software applications are discovered daily. Vendors are constantly updating and patching their products to address newly discovered security vulnerabilities. Organizations (including any contractor to the organization) are required to promptly install security-relevant software updates (e.g., patches, service packs, and hot fixes). Flaws discovered during security assessments, continuous monitoring, incident response activities, or information system error handling must also be addressed expeditiously.\n\nOrganization-defined time periods for updating security-relevant software may vary based on a variety of factors including, for example, the security category of the information system or the criticality of the update (i.e., severity of the vulnerability related to the discovered flaw).\n\nThis requirement will apply to software patch management solutions that are used to install patches across the enclave and also to applications themselves that are not part of that patch management solution. For example, many browsers today provide the capability to install their own patch software. Patch criticality, as well as system criticality will vary. Therefore, the tactical situations regarding the patch management process will also vary. This means that the time period utilized must be a configurable parameter. Time frames for application of security-relevant software updates may be dependent upon the Information Assurance Vulnerability Management (IAVM) process.\n\nThe application, or the patch management solution that is configured to patch the application, must be configured to check for and install security-relevant software updates and patches at least weekly. Patches must be applied immediately or in accordance with POA&Ms, IAVMs, CTOs, DTMs or other authoritative patching guidelines or sources.'),
        ('IA_Controls', ''),
        ('Check_Content', 'Review the application documentation to identify application versions and patching.\n\nInterview the application administrator and inquire about patching process.\n\nReview IAVMs and CTOs to determine if the application is being updated in accordance with authoritative sources.\n\nIf application updates are not checked on at least on a weekly basis and applied immediately or in accordance with POA&Ms, IAVMs, CTOs, DTMs or other authoritative patching guidelines or sources, this is a finding.'),
        ('Fix_Text', 'Check for application updates at least weekly and apply patches immediately or in accordance with POA&Ms, IAVMs, CTOs, DTMs or other authoritative patching guidelines or sources.'),
        ('False_Positives', ''),
        ('False_Negatives', ''),
        ('Documentable', 'false'),
        ('Mitigations', ''),
        ('Potential_Impact', ''),
        ('Third_Party_Tools', ''),
        ('Mitigation_Control', ''),
        ('Responsibility', ''),
        ('Security_Override_Guidance', ''),
        ('Check_Content_Ref', 'M'),
        ('Weight', '10.0'),
        ('Class', 'Unclassified'),
        ('STIGRef', 'Application Security and Development Security Technical Implementation Guide :: Version 6, Release: 4 Benchmark Date: 01 Oct 2025'),
        ('STIG_UUID', '7fab75f4-b164-4cb4-a0c4-c9263b227f93'),
        ('LEGACY_ID', 'SV-84903'),
        ('LEGACY_ID', 'V-70281'),
        ('CCI_REF', 'CCI-002605'),
    ],
    [
        ('Vuln_Num', 'V-222642'),
        ('Severity', 'high'),
        ('Group_Title', 'SRG-APP-000516'),
        ('Rule_ID', 'SV-222642r961863_rule'),
        ('Rule_Ver', 'APSC-DV-003110'),
        ('Rule_Title', 'The application must not contain embedded authentication data.'),
        ('Vuln_Discuss', 'Authentication data stored in code could potentially be read and used by anonymous users to gain access to a backend database or application servers. This could lead to compromise of application data.'),
        ('IA_Controls', ''),
        ('Check_Content', 'Review the application documentation and any available source code; this includes configuration files such as global.asa, if present, scripts, HTML files, and any ASCII files.\n\nIdentify any instances of passwords, certificates, or sensitive data included in code.\n\nIf credentials were found, check the file permissions and ownership of the offending file.\n\nIf access to the folder hosting the file is not restricted to the related application process and administrative users, this is a finding.\n\nThe finding details should note specifically where the offending credentials or data were located and what resources they enabled.'),
        ('Fix_Text', 'Remove embedded authentication data stored in code, configuration files, scripts, HTML file, or any ASCII files.'),
        ('False_Positives', ''),
        ('False_Negatives', ''),
        ('Documentable', 'false'),
        ('Mitigations', ''),
        ('Potential_Impact', ''),
        ('Third_Party_Tools', ''),
        ('Mitigation_Control', ''),
        ('Responsibility', ''),
        ('Security_Override_Guidance', ''),
        ('Check_Content_Ref', 'M'),
        ('Weight', '10.0'),
        ('Class', 'Unclassified'),
        ('STIGRef', 'Application Security and Development Security Technical Implementation Guide :: Version 6, Release: 4 Benchmark Date: 01 Oct 2025'),
        ('STIG_UUID', '5667737d-4ad1-4c44-b749-2d588de5cda1'),
        ('LEGACY_ID', 'SV-84985'),
        ('LEGACY_ID', 'V-70363'),
        ('CCI_REF', 'CCI-002367'),
    ],
    [
        ('Vuln_Num', 'V-222657'),
        ('Severity', 'medium'),
        ('Group_Title', 'SRG-APP-000516'),
        ('Rule_ID', 'SV-222657r961863_rule'),
        ('Rule_Ver', 'APSC-DV-003236'),
        ('Rule_Title', 'The application development team must provide an application incident response plan.'),
        ('Vuln_Discuss', 'An application incident response process is managed by the development team and should include a method for individuals to submit potential security vulnerabilities to the development or maintenance team. \n\nThe plan should dictate what is to be done with the reported vulnerabilities. Reported vulnerabilities must be tracked throughout the process to ensure they are triaged, corrected, and tested. The corresponding update is released to the user community and the user community is notified of the availability of the application update.\n\nWithout an established application incident management plan and process, discovered issues and vulnerabilities will go unreported.   Vulnerabilities will not be triaged and managed, and there may be delays in corrective actions.\n\nInformation on how to submit bug and vulnerability reports must also be included in the application design document or configuration guide.\n\nThis requirement is meant to be applied when reviewing an application with the development team.'),
        ('IA_Controls', ''),
        ('Check_Content', 'If the application is a COTS application and the development team is not accessible to interview this requirement is not applicable.\n\nInterview the application development team members. Request and review the application incident response plan. \n\nEnsure the plan includes an implemented process that:\n\n- Tracks reported vulnerabilities and bugs\n- Confirms reported vulnerabilities and bugs\n- Tracks remediation effort\n- Notifies application users of available updates that address the reported issues.\n\nIf the application incident response plan does not exist and at a minimum does not implement the aforementioned processes, this is a finding.\n'),
        ('Fix_Text', 'The development team creates an application incident response plan documenting and establishing a process that at a minimum:\r\n\r\n- Tracks reported vulnerabilities and bugs\r\n- Confirms reported vulnerabilities and bugs\r\n- Tracks remediation effort\r\n- Notifies application users of available updates that address the reported issues.'),
        ('False_Positives', ''),
        ('False_Negatives', ''),
        ('Documentable', 'false'),
        ('Mitigations', ''),
        ('Potential_Impact', ''),
        ('Third_Party_Tools', ''),
        ('Mitigation_Control', ''),
        ('Responsibility', ''),
        ('Security_Override_Guidance', ''),
        ('Check_Content_Ref', 'M'),
        ('Weight', '10.0'),
        ('Class', 'Unclassified'),
        ('STIGRef', 'Application Security and Development Security Technical Implementation Guide :: Version 6, Release: 4 Benchmark Date: 01 Oct 2025'),
        ('STIG_UUID', '1b5363b9-514a-4013-ac49-de1701686398'),
        ('LEGACY_ID', 'SV-85015'),
        ('LEGACY_ID', 'V-70393'),
        ('CCI_REF', 'CCI-003289'),
    ],
]



def _escape(text: str) -> str:
    """Escape element text the way STIG Viewer (and ``ElementTree``) do, and only that way.

    Three characters are escaped in text content - ``&``, ``<``, ``>`` - and a carriage return
    becomes the numeric reference ``&#xD;`` so that XML line-ending normalisation cannot eat it.
    Quotes are *not* escaped in text; the reference export leaves them literal.
    """
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\r", "&#xD;"))


def _element(depth: int, tag: str, text: str = "") -> str:
    """One tab-indented element on its own line, long form even when empty.

    The indent is built outside the f-string because a backslash inside an f-string expression
    is a syntax error before Python 3.12, and this package targets 3.11.
    """
    indent = "\t" * depth
    return f"{indent}<{tag}>{_escape(text)}</{tag}>\n"


def _renumber(pairs: list[tuple[str, str]], copy: int) -> list[tuple[str, str]]:
    """Give a repeated rule fresh identifiers so ``rules > 6`` still has unique lookup keys.

    Only used to build large checklists for the performance test; ``copy == 0`` is verbatim.
    """
    if copy == 0:
        return pairs
    offset = 1000 * copy
    renumbered = []
    for name, value in pairs:
        if name == "Vuln_Num":
            value = f"V-{int(value[2:]) + offset}"
        elif name == "Rule_ID":
            value = re.sub(r"SV-(\d+)", lambda m: f"SV-{int(m.group(1)) + offset}", value)
        elif name == "Rule_Ver":
            value = f"APSC-DV-{int(value.rsplit('-', 1)[1]) + offset:06d}"
        renumbered.append((name, value))
    return renumbered


def build_ckl(rules: int = 8, statuses: list[str] | None = None, crlf: bool = False,
              asset: dict[str, str] | None = None) -> bytes:
    """Build a CKL imitating STIG Viewer 3.7.0 output, byte layout included.

    ``rules`` above eight cycles :data:`RULES` with renumbered identifiers. ``statuses`` sets one
    ``<STATUS>`` per rule (default ``Not_Reviewed`` throughout). ``crlf=True`` writes CRLF line
    separators, which is what a checklist saved by STIG Viewer 2.x on Windows can look like -
    the ``&#xD;`` entities inside text stay entities either way.
    """
    asset_values = {**DEFAULT_ASSET, **(asset or {})}
    out = io.StringIO()
    out.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    out.write(HEADER_COMMENT + "\n<CHECKLIST>\n\t<ASSET>\n")
    for field in ASSET_FIELDS:
        out.write(_element(2, field, asset_values.get(field, "")))
    out.write("\t</ASSET>\n\t<STIGS>\n\t\t<iSTIG>\n\t\t\t<STIG_INFO>\n")
    for name, value in STIG_INFO:
        out.write("\t\t\t\t<SI_DATA>\n")
        out.write(_element(5, "SID_NAME", name))
        out.write(_element(5, "SID_DATA", value))
        out.write("\t\t\t\t</SI_DATA>\n")
    out.write("\t\t\t</STIG_INFO>\n")

    for index in range(rules):
        pairs = _renumber(RULES[index % len(RULES)], index // len(RULES))
        out.write("\t\t\t<VULN>\n")
        for name, value in pairs:
            out.write("\t\t\t\t<STIG_DATA>\n")
            out.write(_element(5, "VULN_ATTRIBUTE", name))
            out.write(_element(5, "ATTRIBUTE_DATA", value))
            out.write("\t\t\t\t</STIG_DATA>\n")
        status = statuses[index] if statuses and index < len(statuses) else "Not_Reviewed"
        out.write(_element(4, "STATUS", status))
        for tag in ("FINDING_DETAILS", "COMMENTS", "SEVERITY_OVERRIDE", "SEVERITY_JUSTIFICATION"):
            out.write(_element(4, tag))
        out.write("\t\t\t</VULN>\n")

    # No trailing newline after </CHECKLIST>: that is how the reference export ends.
    out.write("\t\t</iSTIG>\n\t</STIGS>\n</CHECKLIST>")
    body = out.getvalue()
    if crlf:
        body = body.replace("\n", "\r\n")
    return body.encode("utf-8")


#: What :func:`build_repo` plants, as ``relative path -> content``. Each file exists to make one
#: probe in ``asd_probes.PROBES`` fire, so a test can assert on ``path:line`` rather than on a
#: count. ``config/settings.py`` holds a credential-shaped literal the evidence tool must mask.
SAMPLE_FILES = {
    "requirements.txt": "requests==2.31.0\nflask==3.0.0\n",          # no lockfile beside it
    "pyproject.toml": '[project]\nname = "demo"\nversion = "0.1.0"\n',
    "app/__init__.py": "",
    "app/http_client.py": (
        "import requests\n\n\n"
        "def fetch(url):\n"
        "    # TLS verification turned off while debugging the staging certificate\n"
        "    return requests.get(url, verify=False, timeout=10)\n"),
    "app/hashing.py": (
        "import hashlib\n\n\n"
        "def fingerprint(value):\n"
        "    return hashlib.md5(value.encode()).hexdigest()\n"),
    "app/queries.py": (
        "def find_user(cursor, name):\n"
        '    cursor.execute("SELECT * FROM users WHERE name = \'" + name + "\'")\n'
        "    return cursor.fetchone()\n"),
    "app/session.py": (
        "SESSION_COOKIE_HTTPONLY = True\n"
        "SESSION_COOKIE_SECURE = False\n"
        "PERMANENT_SESSION_LIFETIME = 900\n"
        "MAX_CONCURRENT_SESSIONS = 2\n"),
    "config/settings.py": (
        "DB_HOST = 'localhost'\n"
        "password = \"hunter2hunter2\"\n"
        "LOG_PATH = 'C:\\\\ProgramData\\\\Demo\\\\logs\\\\audit.log'\n"),
    ".github/workflows/ci.yml": (
        "name: ci\n"
        "on: [push]\n"
        "jobs:\n"
        "  scan:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - run: semgrep --config=auto\n"),
    "SECURITY.md": "# Security policy\n\nReport issues to the security team.\n",
    ".git/config": "[core]\n\tpassword = do-not-read-this\n",         # must never be scanned
    "docs/notes.txt": "Nothing security relevant here.\n",
}


def build_repo(tmp: Path) -> Path:
    """Write a synthetic repository for the evidence probes and return its root.

    Besides :data:`SAMPLE_FILES` it plants three things a probe must *skip*: a 2 MiB text file
    (over the size cap), a file whose first bytes contain NUL (binary), and - on POSIX only -
    a symlink pointing at the parent of the repository root, which is the shape of a path
    escape. Windows is skipped for the symlink because creating one there needs either
    developer mode or elevation, and a fixture must not require either.
    """
    root = tmp / "repo"
    for relative, content in SAMPLE_FILES.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")

    (root / "big.log").write_text("verify=False padding line\n" * 90_000, encoding="utf-8", newline="\n")
    (root / "app" / "blob.bin").write_bytes(b"\x00\x01verify=False\x00" + b"\xff" * 512)
    link = root / "escape"
    try:
        link.symlink_to(tmp.parent, target_is_directory=True)
    except (OSError, NotImplementedError):
        pass          # Windows without developer mode: the symlink test skips itself
    return root
